# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Wendy Tran
tagline:          'Developer's Blog'
description:      'Aspiring full-stack developer. This site documents my learnings and reflections through this journey.'
# url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Wendy Tran'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/twendy00
